// User
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_VERIFICATION_REQUIRED = "LOGIN_VERIFICATION_REQUIRED";
export const RESET_MAIL_RESEND = "RESET_MAIL_RESEND";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const EMAIL_RESEND = "EMAIL_RESEND";
export const USER_LOADED = "USER_LOADED";
export const USER_ERROR = "USER_ERROR";
export const GET_USER_INFO = "GET_USER_INFO";
export const RESET_EMAIL_SENT = "RESET_EMAIL_SENT";
export const RESET_CODE_SUCCESS = "RESET_CODE_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_CODE_DISABLED = "RESET_CODE_DISABLED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATED_PROFILE = "UPDATED_PROFILE";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const FOVIRITE_ADDED = "FOVIRITE_ADDED";
export const FOVIRITE_REMOVED = "FOVIRITE_REMOVED";
export const TEMP_FAV = "TEMP_FAV";
export const CLEAR_USER_LOADING = "CLEAR_USER_LOADING";
export const GET_HOTEL_LOCATION = "GET_HOTEL_LOCATION";
export const USER_INFO_FAIL = "USER_INFO_FAIL";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const GET_FAVORITES = "GET_FAVORITES";
export const SET_FAVORITES_LOADING = "SET_FAVORITES_LOADING";
export const GET_MENUS = "GET_MENUS";
export const ADD_CITY = "ADD_CITY";
// Recommendations
export const SET_RECOMMENDATION_LOADING = "SET_RECOMMENDATION_LOADING";
export const RECOMMENDATION_FAIL = "RECOMMENDATION_FAIL";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const GET_ONE_RECOMMENDATION = "GET_ONE_RECOMMENDATION";
export const GET_HIGHLIGHTED = "GET_HIGHLIGHTED";
export const RESET_PAGE = "RESET_PAGE";
export const GET_NEARBY_RECOMMENDATIONS = "GET_NEARBY_RECOMMENDATIONS";
export const SET_NEARBY_LOADING = "SET_NEARBY_LOADING";
export const SET_HIGHLIGHT_LOADING = "SET_HIGHLIGHT_LOADING";

//Categories
export const SET_CATEGORIES_LOADING = "SET_CATEGORIES_LOADING";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";

//Trends
export const GET_TRENDS = "GET_TRENDS";
export const TRENDS_FAIL = "TRENDS_FAIL";
export const SET_TRENDS_LOADING = "SET_TRENDS_LOADING";

//Boxes
export const SET_BOXES_LOADING = "SET_BOXES_LOADING";
export const SET_HIGHLIGHT_BOXES_LOADING = "SET_HIGHLIGHT_BOXES_LOADING";
export const BOXES_FAIL = "BOXES_FAIL";
export const GET_BOXES = "GET_BOXES";
export const GET_BOXES_HIGHLIGHTED = "GET_BOXES_HIGHLIGHTED";

//Banners
export const SET_BANNERS_LOADING = "SET_BANNERS_LOADING";
export const BANNERS_FAIL = "BANNERS_FAIL";
export const GET_BANNERS = "GET_BANNERS";

//Items
export const SET_ITEMS_LOADING = "SET_ITEMS_LOADING";
export const ITEMS_FAIL = "ITEMS_FAIL";
export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_HIGHLIGHTS = "GET_ITEMS_HIGHLIGHTS";
export const SET_AVAILABILITY_LOADING = "SET_AVAILABILITY_LOADING";
export const SET_CART_LOADING = "SET_CART_LOADING";
export const SET_DATES_LOADING = "SET_DATES_LOADING";
export const GET_DATES = "GET_DATES";
export const GET_NEARBY_ITEMS = "GET_NEARBY_ITEMS";
export const GET_AVAILABILITY = "GET_AVAILABILITY";
export const NO_ACTION = "NO_ACTION";
export const SET_CART = "SET_CART";
export const CART_FAIL = "CART_FAIL";
export const CANCEL_ITEM = "CANCEL_ITEM";
export const GET_SINGLE_ITEM = "GET_SINGLE_ITEM";

//Alert
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT = "SET_ALERT";

//Clearings
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_DATA = "CLEAR_DATA";

//Booking
export const GET_BOOKING_AVAILABILITY = "GET_BOOKING_AVAILABILITY";
export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const CANCEL_RESERVATION = "CANCEL_RESERVATION";
export const UNAUTHENTICATED_BOOKING = "UNAUTHENTICATED_BOOKING";
export const BOOKING_FAIL = "BOOKING_FAIL";
export const RESERVE = "RESERVE";
export const BOOK = "BOOK";
export const GET_ITEMS_BOOKINGS = "GET_ITEMS_BOOKINGS";
export const GET_EXPERIENCES_BOOKINGS = "GET_EXPERIENCES_BOOKINGS";

//Loading
export const LOADING = "LOADING";
export const GET_BROWSER = "GET_BROWSER";

//Fails
export const FAIL = "FAIL";

//Experiences
export const SET_EXPERIENCES_LOADING = "SET_EXPERIENCES_LOADING";
export const GET_EXPERIENCES = "GET_EXPERIENCES";
export const GET_SINGLE_EXPERIENCE = "GET_SINGLE_EXPERIENCE";
export const EXPERIENCES_FAIL = "EXPERIENCES_FAIL";
export const SET_STOPS = "SET_STOPS";
export const SET_EXP_ID = "SET_EXP_ID";
export const ADD_TO_ORDERS = "ADD_TO_ORDERS";
export const SET_CART_DETAILS = "SET_CART_DETAILS";
export const PERSONAL_DATA_LOADING = "PERSONAL_DATA_LOADING";

//NoOps
export const GET_TOP_INFO = "GET_TOP_INFO";
export const TOP_INFO_FAIL = "TOP_INFO_FAIL";
export const GET_NEWS = "GET_NEWS";
export const GET_ONE_NEWS = "GET_ONE_NEWS";
